version: "3"
services:
  display-bookings:
    build: .
    ports:
      - 8080:8080
    environment:
      KUMULUZEE_CONFIG_CONSUL_AGENT: http://consul:8500
      KUMULUZEE_DISCOVERY_CONSUL_AGENT: http://consul:8500
    depends_on:
      - consul
  consul:
    image: consul
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600
  accommodations:
      image: janerz6/accommodations
      ports:
        - 8081:8081
      environment:
        - CONFIG_SERVER_URL =http://consul:8500
        - DISCOVERY_HOSTNAME =accommodations
      depends_on:
        - consul