kumuluzee:
  name: display-bookings
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8080
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    consul:
      agent: http://localhost:8500
  discovery:
    ttl: 20
    ping-interval: 15
    consul:
      agent: http://localhost:8500
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      disk-space-health-check:
        threshold: 100000000
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
    web-instrumentation:
      - name: metrics-endpoint
        url-pattern: /metrics/*
      - name: bookings-endpoint
        url-pattern: /v1/bookings/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="orders">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <Socket name="logstash" host="3be32791-a428-460f-b145-a36854a987d0-ls.logit.io" port="17211" protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <!-- Default logger -->
                          <Root level="all">
                              <AppenderRef ref="console" level="info"/>
                              <AppenderRef ref="logstash" level="trace"/>
                          </Root>
                      </Loggers>
                  </Configuration>'

bookings-config:
  insert-enabled: true
  healthy: true