kumuluzee:
  name: display-bookings
  version: 1.0.0
  env:
    name: dev
  config:
      start-retry-delay-ms: 500
      max-retry-delay-ms: 900000
      consul:
        agent: http://192.168.99.100:8500
      #etcd:
      #  hosts: http://192.168.99.100:2379

bookings-config:
  insert-enabled: true