apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: display-bookings-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rso
    spec:
      containers:
      - image: urosbajc/display-bookings
        name: display-bookings
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_CONSUL_AGENT
            value: http://consul:8500
          - name: KUMULUZEE_CONFIG_CONSUL_AGENT
            value: http://consul:8500
          #- name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          #  value: jdbc:postgresql://postgres-customers:5432/customer
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: display-bookings
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: display-bookings