apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: display-bookings-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: display-bookings
    spec:
      containers:
      - image: urosbajc/display-bookings:0.6.1
        name: display-bookings
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://display-bookings:8080
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        resources:
          requests:
            cpu: 200m
