apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: display-bookings-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: display-bookings
    spec:
      containers:
      - image: urosbajc/display-bookings:latest
        name: display-bookings
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_CONSUL_AGENT
            value: http://consul:8500
          - name: KUMULUZEE_CONFIG_CONSUL_AGENT
            value: http://consul:8500
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://display-bookings:8080
          #- name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          #  value: jdbc:postgresql://postgres-customers:5432/customer
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        resources:
          requests:
            cpu: 250m
