# prometheus
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      team: displaybookingsteam
  resources:
    requests:
      memory: 400Mi

---
# monitoring
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: display-bookings
  labels:
    team: displaybookingsteam
spec:
  selector:
    matchLabels:
      app: display-bookings
  endpoints:
  - port: server
